server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

  - job_name: fibonacci-api

    static_configs:
      - targets:
          - localhost

        labels:
          job: fibonacci-api
          service: fibonacci-api
          __path__: /app/logs/*.log

    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>.*?) \| (?P<level>.*?) \| trace=(?P<trace>[a-f0-9-]+) \| span=(?P<span>[a-f0-9-]+) \| (?P<message>.*)$'

      - labels:
          level:
          trace:
          span:

      - output:
          source: message